name: Deploy to Salesforce Sandbox

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > auth_url.txt
          sfdx auth:sfdxurl:store -f auth_url.txt -a DEVORGFORPRIVATEPROJECT

      - name: Convert source to metadata format
        run: sfdx force:source:convert -d mdapi_output_dir -r force-app

      - name: Deploy to Sandbox
        run: sfdx force:mdapi:deploy -d mdapi_output_dir -u DEVORGFORPRIVATEPROJECT -w 10 -l RunLocalTests
